name: Build and Upload Executable

on:
  push:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    environment: executable

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Export environment variables
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          echo "SUPABASE_URL=${SUPABASE_URL}" > .env
          echo "SUPABASE_KEY=${SUPABASE_KEY}" >> .env

      - name: Validate environment variables
        run: |
          echo "Checking .env contents:"
          cat .env
          echo "Checking SUPABASE_URL:"
          grep "SUPABASE_URL" .env || (echo "SUPABASE_URL not found" && exit 1)
          echo "Checking SUPABASE_KEY:"
          grep "SUPABASE_KEY" .env || (echo "SUPABASE_KEY not found" && exit 1)

      - name: Build Executable for Linux
        run: |
          pyinstaller --noconfirm anylabeling.spec

      - name: Upload Linux executable as artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-executable
          path: dist/

  build-macos:
    runs-on: macos-14.5
    environment: executable

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11.3"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Export environment variables
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          echo "SUPABASE_URL=$SUPABASE_URL" >> $GITHUB_ENV
          echo "SUPABASE_KEY=$SUPABASE_KEY" >> $GITHUB_ENV

      - name: Build Executable for macOS
        run: |
          pyinstaller --noconfirm anylabeling.spec

      - name: Upload macOS executable as artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-executable
          path: dist/