name: New Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        device: [CPU, GPU]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - uses: conda-incubator/setup-miniconda@v2
        with:
          python-version: "3.10.14"
          miniconda-version: "latest"

      - name: Set preferred device
        shell: bash -l {0}
        run: >-
          sed -i'' -e 's/\_\_preferred_device\_\_[ ]*=[ ]*\"[A-Za-z0-9]*\"/__preferred_device__ = "${{ matrix.device }}"/g' anylabeling/app_info.py

      - name: Install main
        shell: bash -l {0}
        run: |
          pip install .

      - name: Install PyQt5 for macOS
        shell: bash -l {0}
        run: |
          conda install -c conda-forge pyqt==5.15.7
        if: runner.os == 'macOS'

      - name: Export environment variables
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: |
          echo "SUPABASE_URL=${SUPABASE_URL}" > .env
          echo "SUPABASE_KEY=${SUPABASE_KEY}" >> .env

      - name: Validate environment variables
        run: |
          echo "Checking .env contents:"
          cat .env
          echo "Checking SUPABASE_URL:"
          grep "SUPABASE_URL" .env || (echo "SUPABASE_URL not found" && exit 1)
          echo "Checking SUPABASE_KEY:"
          grep "SUPABASE_KEY" .env || (echo "SUPABASE_KEY not found" && exit 1)

      - name: Run pyinstaller
        shell: bash -l {0}
        run: |
          pip install pyinstaller
          pyinstaller --noconfirm anylabeling.spec

      - name: Upload release executable on macOS & Linux
        id: upload_release_executable_macos_linux
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }}
          asset_path: ./dist/anylabeling
          asset_name: AnyLabeling-${{ runner.os }}${{ matrix.device == 'GPU' && '-GPU' || '' }}
          asset_content_type: application/octet-stream
        if: runner.os != 'Windows'

      - name: Upload Windows executable as artifact
        uses: actions/upload-artifact@v3
        with:
          name: Windows-executable
          path: dist/anylabeling.exe
        if: runner.os == 'Windows'

      - name: Create dmg for macOS
        run: |
          npm install -g create-dmg
          cd dist
          create-dmg AnyLabeling.app || test -f AnyLabeling\ 0.0.0.dmg
          mv AnyLabeling\ 0.0.0.dmg AnyLabeling${{ matrix.device == 'GPU' && '-GPU' || '' }}.dmg
        if: runner.os == 'macOS'

      - name: Upload release app on macOS
        id: upload_release_app_macos
        uses: actions/upload-artifact@v3
        with:
          name: macos-executable
          path: dist/./dist/AnyLabeling${{ matrix.device == 'GPU' && '-GPU' || '' }}.dmg
        if: runner.os == 'macOS'
