name: Build and Upload Executable

on:
  push:
    branches:
      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Build Executable for Linux
        run: |
          pyinstaller --onefile anylabeling/app.py

      - name: Upload Linux executable as artifact
        uses: actions/upload-artifact@v3
        with:
          name: linux-executable
          path: dist/app

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Build Executable for macOS
        run: |
          pyinstaller --onefile anylabeling/app.py

      - name: Upload macOS executable as artifact
        uses: actions/upload-artifact@v3
        with:
          name: macos-executable
          path: dist/app

  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.7'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt

      - name: Build Executable for Windows
        run: |
          pyinstaller --onefile anylabeling/app.py

      - name: Upload Windows executable as artifact
        uses: actions/upload-artifact@v3
        with:
          name: windows-executable
          path: dist/app.exe
